name:  PageMooSlider
author:  Lexx
current:  1.0
category:  Plugin 
tags:  [slider,page,navigation]
docs:  http://cleverscript.ru/index.php/javascript/mootools/15-pagemooslider
demo:  http://cleverscript.ru/demo/javascript/mootools/pagemooslider/index.html